# Generated by Django 4.1.1 on 2022-10-10 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('amount_usd', models.CharField(max_length=255)),
                ('amount_asset', models.CharField(max_length=255)),
                ('asset', models.CharField(max_length=255)),
                ('tx_id', models.CharField(db_index=True, max_length=255)),
                ('block_id', models.CharField(blank=True, max_length=255, null=True)),
                ('vin', models.CharField(blank=True, max_length=255, null=True)),
                ('vout', models.CharField(blank=True, max_length=255, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(default=dict)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='wallet.address')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('address', 'tx_id', 'vin', 'vout'), name='transaction_unique'),
        ),
    ]
