# Generated by Django 4.1.7 on 2023-03-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputdata',
            name='vin_vout',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outputdata',
            name='vin_vout',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
