# Generated by Django 4.1.1 on 2022-12-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=255)),
                ('amount_usd', models.CharField(max_length=255)),
                ('interval', models.IntegerField(choices=[(1, 'Daily'), (2, '5 min')])),
                ('time', models.DateTimeField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
